import type { Entity } from './schemas';
export const catalog: Record<Entity, { title: string; description: string; fields: string[] }> = {
  members: {
    title: 'Anggota',
    description: 'Daftar anggota dan status keanggotaan.',
    fields: ['title', 'member_number', 'date', 'contact', 'address', 'status', 'notes'],
  },
  'cash-entries': {
    title: 'Buku kas',
    description: 'Catatan uang masuk dan keluar. Ringkasan berdasarkan transaksi yang dicatat.',
    fields: [
      'title',
      'date',
      'direction',
      'amount',
      'category',
      'account',
      'member_id',
      'item_id',
      'unit_id',
      'reference_number',
      'link',
      'notes',
    ],
  },
  'inventory-items': {
    title: 'Barang',
    description: 'Daftar barang dan stok buku untuk pembanding saat opname.',
    fields: [
      'title',
      'sku',
      'price',
      'unit_id',
      'measurement',
      'rack',
      'book_quantity',
      'minimum_quantity',
      'notes',
    ],
  },
  'stock-counts': {
    title: 'Stok opname',
    description: 'Bandingkan stok buku dengan hasil hitung fisik. Stok buku tidak diubah otomatis.',
    fields: ['title', 'item_id', 'date', 'book_quantity', 'counted_quantity', 'assignee', 'notes'],
  },
  organization: {
    title: 'Profil koperasi',
    description: 'Identitas dan profil koperasi.',
    fields: [
      'title',
      'village',
      'district',
      'regency',
      'province',
      'manager',
      'start_date',
      'target_date',
    ],
  },
  workstreams: {
    title: 'Proyek & bidang kerja',
    description: 'Daftar proyek, tujuan, dan tugas terkait.',
    fields: [
      'title',
      'code',
      'description',
      'assignee',
      'status',
      'priority',
      'start_date',
      'target_date',
      'color',
      'notes',
    ],
  },
  milestones: {
    title: 'Milestone',
    description: 'Hasil penting yang perlu dicapai dalam tiap tahap.',
    fields: ['title', 'workstream_id', 'due_date', 'actual_date', 'notes'],
  },
  'work-items': {
    title: 'Tugas',
    description: 'Daftar tugas, penanggung jawab, dan tenggat.',
    fields: [
      'title',
      'description',
      'workstream_id',
      'milestone_id',
      'sprint_id',
      'unit_id',
      'stakeholder_id',
      'document_id',
      'meeting_id',
      'issue_id',
      'assignee',
      'start_date',
      'due_date',
      'status',
      'priority',
      'poac',
      'recurrence',
      'recurrence_time',
      'recurrence_end_date',
      'subtasks',
      'dependencies',
      'link',
      'notes',
    ],
  },
  sprints: {
    title: 'Target periode',
    description: 'Target kerja koperasi untuk periode mingguan atau bulanan.',
    fields: ['title', 'goal', 'duration', 'start_date', 'end_date', 'status', 'notes'],
  },
  units: {
    title: 'Gerai',
    description: 'Pantau kesiapan pembukaan gerai secara bertahap.',
    fields: [
      'title',
      'kind',
      'assignee',
      'location',
      'status',
      'slot',
      'physical',
      'equipment',
      'sop',
      'staff',
      'link',
      'notes',
    ],
  },
  checklist: {
    title: 'Kesiapan',
    description: 'Pemeriksaan kelengkapan dan bukti pekerjaan.',
    fields: [
      'title',
      'workstream_id',
      'unit_id',
      'dimension',
      'required',
      'status',
      'evidence',
      'link',
    ],
  },
  stakeholders: {
    title: 'Mitra & kontak',
    description: 'Orang dan lembaga yang perlu dihubungi.',
    fields: ['title', 'category', 'contact', 'last_contact', 'follow_up'],
  },
  interactions: {
    title: 'Riwayat interaksi',
    description: 'Riwayat komunikasi dan tindak lanjut.',
    fields: ['title', 'stakeholder_id', 'date', 'notes', 'follow_up'],
  },
  meetings: {
    title: 'Rapat & notulen',
    description: 'Agenda, tautan rapat online, notulen, dan tindak lanjut.',
    fields: [
      'title',
      'date',
      'time',
      'duration',
      'mode',
      'location',
      'meeting_url',
      'participants',
      'agenda',
      'minutes',
    ],
  },
  decisions: {
    title: 'Keputusan',
    description: 'Risalah keputusan dan keterangannya.',
    fields: ['title', 'meeting_id', 'date', 'reason', 'link'],
  },
  documents: {
    title: 'Dokumen & legalitas',
    description: 'Daftar dokumen dan masa berlakunya.',
    fields: ['title', 'kind', 'number', 'issued_date', 'expires_date', 'status', 'link', 'notes'],
  },
  risks: {
    title: 'Risiko',
    description: 'Daftar risiko dan rencana mitigasi.',
    fields: ['title', 'probability', 'impact', 'mitigation', 'assignee', 'review_date', 'status'],
  },
  issues: {
    title: 'Isu lapangan',
    description: 'Kendala operasional dan tindakan penyelesaian.',
    fields: ['title', 'description', 'assignee', 'due_date', 'status'],
  },
  staff: {
    title: 'Tim gerai',
    description: 'Daftar petugas, peran, dan penempatan.',
    fields: ['title', 'role', 'unit_id', 'status'],
  },
  trainings: {
    title: 'Pelatihan',
    description: 'Jadwal dan status pelatihan petugas.',
    fields: ['title', 'staff_id', 'date', 'required', 'status', 'notes'],
  },
  journal: {
    title: 'Kegiatan',
    description: 'Catatan apa yang terjadi: kunjungan, koordinasi, hasil lapangan.',
    fields: ['title', 'date', 'notes', 'unit_id', 'work_item_id', 'stakeholder_id', 'meeting_id'],
  },
};
export const labels: Record<string, string> = {
  duration: 'Durasi (menit)',
  slot: 'Lahan di Dunia Koperasi',
  rack: 'Rak gudang',
  member_number: 'Nomor anggota',
  address: 'Alamat',
  direction: 'Jenis transaksi',
  amount: 'Nominal (Rp)',
  category: 'Kategori',
  account: 'Kas / rekening',
  reference_number: 'Nomor bukti',
  sku: 'Kode barang',
  measurement: 'Satuan',
  book_quantity: 'Stok buku',
  minimum_quantity: 'Batas stok minimum',
  counted_quantity: 'Hasil hitung fisik',
  item_id: 'Barang',
  mode: 'Jenis rapat',
  meeting_url: 'Tautan rapat online',
  title: 'Nama / judul',
  village: 'Desa',
  district: 'Kecamatan',
  regency: 'Kabupaten',
  province: 'Provinsi',
  manager: 'Nama manajer',
  start_date: 'Tanggal mulai',
  target_date: 'Target pembukaan',
  code: 'Kode',
  color: 'Warna',
  description: 'Uraian',
  workstream_id: 'Proyek / bidang kerja',
  milestone_id: 'Milestone',
  unit_id: 'Gerai',
  assignee: 'Penanggung jawab',
  due_date: 'Tenggat',
  status: 'Status',
  priority: 'Prioritas',
  poac: 'Kategori POAC',
  recurrence: 'Pengulangan',
  subtasks: 'Subtugas',
  dependencies: 'Prasyarat',
  link: 'Link pengumpulan / bukti hasil',
  notes: 'Catatan',
  actual_date: 'Tanggal tercapai',
  kind: 'Jenis',
  location: 'Lokasi',
  physical: 'Kondisi fisik',
  equipment: 'Peralatan',
  sop: 'Kesiapan SOP',
  staff: 'Kesiapan petugas',
  dimension: 'Dimensi',
  required: 'Wajib',
  evidence: 'Bukti pekerjaan',
  contact: 'Kontak profesional',
  influence: 'Pengaruh (1–5)',
  interest: 'Minat (1–5)',
  last_contact: 'Kontak terakhir',
  follow_up: 'Tindak lanjut',
  stakeholder_id: 'Mitra atau kontak',
  document_id: 'Dokumen atau kontrak',
  issue_id: 'Kendala terkait',
  date: 'Tanggal',
  time: 'Waktu WIB',
  participants: 'Peserta',
  agenda: 'Agenda',
  minutes: 'Notulen',
  meeting_id: 'Rapat',
  reason: 'Alasan keputusan',
  number: 'Nomor dokumen',
  issued_date: 'Tanggal terbit',
  expires_date: 'Berlaku sampai',
  probability: 'Peluang (1–5)',
  impact: 'Dampak (1–5)',
  mitigation: 'Mitigasi',
  review_date: 'Tanggal tinjau',
  role: 'Peran',
  staff_id: 'Petugas',
  work_item_id: 'Tugas terkait',
  goal: 'Tujuan target',
  sprint_id: 'Target periode',
  recurrence_time: 'Jam perulangan',
  recurrence_end_date: 'Selesai berulang',
  member_id: 'Anggota terkait (opsional)',
  price: 'Harga satuan (Rp)',
  cash_summary: 'Transaksi Kas',
  relation: 'Terkait',
  stock_status: 'Kondisi Stok',
};
export const references: Record<string, Entity> = {
  item_id: 'inventory-items',
  member_id: 'members',
  issue_id: 'issues',
  workstream_id: 'workstreams',
  milestone_id: 'milestones',
  sprint_id: 'sprints',
  unit_id: 'units',
  stakeholder_id: 'stakeholders',
  document_id: 'documents',
  meeting_id: 'meetings',
  staff_id: 'staff',
  work_item_id: 'work-items',
};
export const options: Record<string, string[]> = {
  'members.status': ['aktif', 'nonaktif'],
  direction: ['masuk', 'keluar'],
  mode: ['tatap muka', 'online', 'hybrid'],
  'workstreams.status': ['rencana', 'aktif', 'ditunda', 'selesai', 'diarsipkan'],
  'work-items.status': ['rencana', 'proses', 'selesai', 'dibatalkan'],
  'sprints.status': ['rencana', 'aktif', 'selesai'],
  'sprints.duration': ['1 minggu', '2 minggu', '1 bulan', 'kustom'],
  'checklist.status': ['rencana', 'proses', 'selesai'],
  'units.status': ['rencana', 'persiapan', 'siap uji', 'siap buka', 'aktif'],
  'units.slot': ['otomatis', '1', '2', '3', '4', '5', '6', '7'],
  'inventory-items.rack': ['belum ditentukan', 'A', 'B', 'C', 'D', 'E', 'F'],
  'documents.status': ['belum ada', 'diproses', 'tersedia'],
  'risks.status': ['terbuka', 'ditangani', 'ditutup'],
  'issues.status': ['terbuka', 'ditangani', 'ditutup'],
  'staff.status': ['direncanakan', 'ditunjuk', 'aktif', 'nonaktif'],
  'trainings.status': ['rencana', 'selesai'],
  priority: ['rendah', 'normal', 'tinggi', 'mendesak'],
  poac: ['planning', 'organizing', 'actuating', 'controlling'],
  recurrence: ['tidak', 'harian', 'mingguan', 'bulanan'],
  dimension: ['legalitas', 'fisik', 'sdm', 'sop', 'sistem'],
  'stakeholders.category': [
    'Agrinas',
    'PIC lapangan / Babinsa',
    'Pengurus dan pengawas koperasi',
    'Pemerintah desa',
    'Mitra usaha',
    'Lainnya',
  ],
};
export const choiceLabels: Record<string, string> = {
  // Status
  rencana: 'Rencana',
  proses: 'Dikerjakan',
  selesai: 'Selesai',
  dibatalkan: 'Dibatalkan',
  aktif: 'Aktif',
  ditunda: 'Ditunda',
  diarsipkan: 'Diarsipkan',
  draft: 'Draf',
  siap: 'Siap',
  antrean: 'Antrean',
  menunggu: 'Menunggu',
  persiapan: 'Persiapan',
  'siap uji': 'Siap Uji',
  'siap buka': 'Siap Buka',
  'belum ada': 'Belum Ada',
  diproses: 'Sedang Diproses',
  tersedia: 'Tersedia',
  terbuka: 'Terbuka',
  ditangani: 'Sedang Ditangani',
  ditutup: 'Ditutup',
  direncanakan: 'Direncanakan',
  ditunjuk: 'Ditunjuk',
  nonaktif: 'Nonaktif',
  terlambat: 'Terlambat',

  // Prioritas
  rendah: 'Rendah',
  normal: 'Normal',
  tinggi: 'Tinggi',
  mendesak: 'Mendesak',

  // Jenis Kas
  masuk: 'Uang Masuk (+)',
  keluar: 'Uang Keluar (-)',

  // Mode Rapat
  'tatap muka': 'Tatap Muka',
  online: 'Online',
  hybrid: 'Hybrid',

  // Durasi Target Periode
  '1 minggu': '1 Minggu',
  '2 minggu': '2 Minggu',
  '1 bulan': '1 Bulan',
  kustom: 'Kustom',

  // POAC
  planning: 'Planning (Perencanaan)',
  organizing: 'Organizing (Pengorganisasian)',
  actuating: 'Actuating (Pelaksanaan)',
  controlling: 'Controlling (Pengawasan)',

  // Perulangan
  tidak: 'Tidak Berulang',
  harian: 'Harian (Setiap Hari)',
  mingguan: 'Mingguan (Setiap Minggu)',
  bulanan: 'Bulanan (Setiap Bulan)',

  // Dimensi Kesiapan
  legalitas: 'Legalitas',
  fisik: 'Fisik',
  sdm: 'SDM / Petugas',
  sop: 'SOP / Tata Kelola',
  sistem: 'Sistem & Peralatan',
};

export function formatChoiceLabel(value: string): string {
  if (!value) return '';
  if (choiceLabels[value]) return choiceLabels[value];
  return value
    .split(' ')
    .map((word) => (word ? word.charAt(0).toUpperCase() + word.slice(1).toLowerCase() : ''))
    .join(' ');
}

export const navigation = [
  ['/beranda', 'Beranda', ''],
  ['/dunia-koperasi', 'Dunia Koperasi', ''],
  ['/hari-ini', 'Hari Ini', ''],
  ['/tugas', 'Daftar Tugas', ''],
  ['/tindak-lanjut', 'Perlu Perhatian', ''],
  ['/proyek', 'Proyek', ''],
  ['/roadmap', 'Linimasa', ''],
  ['/jurnal', 'Kegiatan', ''],
  ['/pencatatan', 'Ringkasan Buku', ''],
  ['/keuangan', 'Buku Kas', ''],
  ['/barang', 'Barang Dagangan', ''],
  ['/stok-opname', 'Stok Opname', ''],
  ['/anggota', 'Buku Anggota', ''],
  ['/gerai', 'Unit Gerai', ''],
  ['/kesiapan', 'Kesiapan Gerai', ''],
  ['/risiko', 'Risiko & Isu', ''],
  ['/laporan', 'Laporan Kerja', ''],
  ['/rapat', 'Rapat & Keputusan', ''],
  ['/dokumen', 'Dokumen', ''],
  ['/mitra', 'Mitra & Kontak', ''],
  ['/tim', 'Tim & Petugas', ''],
  ['/pengaturan', 'Pengaturan', ''],
  ['/panduan', 'Panduan', ''],
] as const;
export const pages: Record<string, Entity[]> = {
  tugas: ['work-items'],
  kesiapan: ['checklist'],
  gerai: ['units'],
  pemangku: ['stakeholders', 'interactions'],
  mitra: ['stakeholders', 'interactions'],
  rapat: ['meetings', 'decisions'],
  dokumen: ['documents'],
  risiko: ['risks', 'issues'],
  tim: ['staff', 'trainings'],
  jurnal: ['journal'],
  pengaturan: ['organization', 'workstreams'],
};
